spring.application.name=JPA_Relation_ExerciseI


server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/jpa
spring.datasource.username=root

spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always